name: CI

on:
  push:
    branches: [master, next, next-major, beta, alpha]
  pull_request:
    branches: [master, next, next-major, beta, alpha]
  schedule:
    - cron: "0 9 * * *"

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deps
        run: docker-compose build release
      - name: Tests
        run: ./tests.sh
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # - name: Release
      #   if: ${{ github.event_name != 'pull_request' }}
      #   run: docker-compose run $CI_ENV release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.NCDC_GITHUB_RELEASE_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
