name: CI

on:
  push:
    branches: [master, next, next-major, beta, alpha]
  pull_request:
    branches: [master, next, next-major, beta, alpha]
  schedule:
    - cron: "0 9 * * *"

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deps
        run: docker-compose build release

      - name: Linting
        run: docker-compose run lint
      - name: Typecheck
        run: docker-compose run typecheck

      - name: Tests
        run: docker-compose run cover
      - name: Copy coverage reports
        run: docker cp $(docker-compose ps -qa cover):/usr/src/app/coverage ./coverage
      - name: Upload coverage
        run: ./upload-coverage.sh $GITHUB_EVENT_PATH
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Release
        if: ${{ github.event_name != 'pull_request' }}
        run: docker-compose run release
        env:
          GITHUB_TOKEN: ${{ secrets.NCDC_GITHUB_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
