name: CI

on:
  push:
    branches: [master, next, next-major, beta, alpha]
  pull_request:
    branches: [master, next, next-major, beta, alpha]
  schedule:
    - cron: "0 9 * * *"

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build deps
        run: docker-compose build release
      - name: Get codecov env
        run: echo "::set-env name=CI_ENV::$(eval bash <(curl -s https://codecov.io/env))"
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Linting
        run: docker-compose run lint
      - name: Typecheck
        run: docker-compose run typecheck
      - name: Coverage
        run: docker-compose run $CI_ENV cover

      - name: Release
        if: ${{ github.event_name != 'pull_request' }}
        run: - docker-compose run $CI_ENV release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
