name: Support latest typescript version
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,18 * * *"
jobs:
  upgrade:
    name: Upgrade and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - name: Install dependencies
        run: npm ci
      - name: Get current version number
        run: echo "::set-output name=version::$(npx tsc --version | sed 's/Version //g')"
        id: current_version_check
      - name: Install latest ts version
        run: npm i -D typescript@4.*
      - name: Get updated version number
        run: echo "::set-output name=version::$(npx tsc --version | sed 's/Version //g')"
        id: updated_version_check
      - name: Install required ts dependencies
        if: ${{ steps.current_version_check.outputs.version != steps.updated_version_check.outputs.version }}
        run: |
          npm i --prefix ./black-box-tests/pre-release typescript@4.*
          npm i ts-json-schema-generator@latest
      - name: Create pull request
        if: ${{ steps.current_version_check.outputs.version != steps.updated_version_check.outputs.version }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.NCDC_GITHUB_TOKEN }}
          commit-message: "feat(deps): add support for typescript ${{ steps.updated_version_check.outputs.version }}"
          title: Add support for Typescript ${{ steps.updated_version_check.outputs.version }}
          base: master
          branch: bump-ts-version
          labels: merge
